//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANGs
    {
        public KHACHHANGs()
        {
            this.DONHANGs = new HashSet<DONHANGs>();
        }
    
        public int MAKH { get; set; }
        public Nullable<int> MATK { get; set; }
        public string TENKH { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
    
        public virtual ICollection<DONHANGs> DONHANGs { get; set; }
        public virtual TAIKHOANs TAIKHOANs { get; set; }
    }
}
