//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMs
    {
        public SANPHAMs()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANGs>();
            this.CHITIETKMs = new HashSet<CHITIETKMs>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string HINHLON { get; set; }
        public string HINHNHO { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> MATH { get; set; }
        public string DANHGIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MALOAISP { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual ICollection<CHITIETDONHANGs> CHITIETDONHANGs { get; set; }
        public virtual ICollection<CHITIETKMs> CHITIETKMs { get; set; }
        public virtual LOAISANPHAMs LOAISANPHAMs { get; set; }
        public virtual THUONGHIEUx THUONGHIEUx { get; set; }
    }
}
