//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOANs
    {
        public TAIKHOANs()
        {
            this.KHACHHANGs = new HashSet<KHACHHANGs>();
        }
    
        public int MATK { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string MALOAITK { get; set; }
    
        public virtual ICollection<KHACHHANGs> KHACHHANGs { get; set; }
        public virtual LOAITKs LOAITKs { get; set; }
    }
}
