//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDongHo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUONGHIEUx
    {
        public THUONGHIEUx()
        {
            this.SANPHAMs = new HashSet<SANPHAMs>();
        }
    
        public int MATH { get; set; }
        public string TENTH { get; set; }
        public string HINHTH { get; set; }
    
        public virtual ICollection<SANPHAMs> SANPHAMs { get; set; }
    }
}
